In [199]:
import numpy as np
import pandas as pd

In [176]:
df = pd.read_excel("G:\\ecommerce-sales-prediction\\data\\raw\\Online Retail.xlsx")
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [177]:
df.shape

(541909, 8)

In [178]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [179]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [180]:
df.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,541909.000000,541909,541909.000000,406829.000000
mean,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.081158,NaN,96.759853,1713.600303

In [181]:
cancellation = df['InvoiceNo'].astype(str).str.startswith("C")
cancellation.sum()

9288

In [182]:
cancellation_percent = cancellation.mean() * 100
cancellation_percent

1.7139409015166756

In [183]:
(df['Quantity'] < 0).sum()

10624

In [184]:
df[df['Quantity'] < 0].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom

In [185]:
df[df['UnitPrice'] < 0].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

In [186]:
df['Revenue'] = df['Quantity'] * df['UnitPrice']
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [187]:
df['Revenue'].describe()

count    541909.000000
mean         17.987795
std         378.810824
min     -168469.600000
25%           3.400000
50%           9.750000
75%          17.400000
max      168469.600000
Name: Revenue, dtype: float64

In [188]:
quality_report = pd.DataFrame({
    "dtype" : df.dtypes.astype(str),
    "missing_count" : df.isnull().sum().values,
    "missing_percent" : (df.isnull().sum() / len(df)) * 100,
    "unique_values" : df.nunique().values
})
quality_report

                      dtype  missing_count  missing_percent  unique_values
InvoiceNo            object              0         0.000000          25900
StockCode            object              0         0.000000           4070
Description          object           1454         0.268311           4223
Quantity              int64              0         0.000000            722
InvoiceDate  datetime64[ns]              0         0.000000          23260
UnitPrice           float64              0         0.000000           1630
CustomerID          float64         135080        24.926694           4372
Country              object              0         0.000000             38
Revenue             float64              0         0.000000           6204

In [189]:
df_clean = df.dropna(subset=["CustomerID"]).copy()
df_clean = df_clean.drop_duplicates().reset_index(drop=True)
df_clean["Revenue"] = df_clean["Quantity"] * df_clean["UnitPrice"]
df_clean["CustomerID"] = df_clean["CustomerID"].astype(int)
msk = df_clean["InvoiceNo"].astype(str).str.startswith("C")
df_clean = df_clean[~msk]
df_clean.shape

(392732, 9)

In [190]:
print("Original rows:", len(df))
print("Cleaned rows:", len(df_clean))
print("Removed rows:", len(df) - len(df_clean))
removed_percent = ((len(df) - len(df_clean)) / len(df)) * 100
print(f"Removed: {removed_percent:.2f}%")

Original rows: 541909
Cleaned rows: 392732
Removed rows: 149177
Removed: 27.53%

In [191]:
df_clean.groupby("StockCode")["Description"].nunique().sort_values(ascending=False).value_counts()

Description
1    3452
2     196
3      15
4       2
Name: count, dtype: int64

In [192]:
df_clean.groupby("CustomerID")["Country"].nunique().sort_values(ascending=False).value_counts()

Country
1    4331
2       8
Name: count, dtype: int64

In [193]:
customers = df_clean[["CustomerID", "Country"]].drop_duplicates(subset=["CustomerID"]).reset_index(drop=True)
customers.tail()

      CustomerID         Country
4334       13436  United Kingdom
4335       15520  United Kingdom
4336       13298  United Kingdom
4337       14569  United Kingdom
4338       12713         Germany

In [194]:
products = df_clean[["StockCode", "Description"]].drop_duplicates(subset=["StockCode"]).reset_index(drop=True)
products.tail()

     StockCode                     Description
3660    90214U       LETTER "U" BLING KEY RING
3661    90214W       LETTER "W" BLING KEY RING
3662    90214Z       LETTER "Z" BLING KEY RING
3663     90089  PINK CRYSTAL SKULL PHONE CHARM
3664     23843     PAPER CRAFT , LITTLE BIRDIE

In [195]:
invoices = df_clean[["InvoiceNo", "CustomerID", "InvoiceDate"]].drop_duplicates(subset=["InvoiceNo"]).reset_index(drop=True)
invoices.tail()

      InvoiceNo  CustomerID         InvoiceDate
18531    581583       13777 2011-12-09 12:23:00
18532    581584       13777 2011-12-09 12:25:00
18533    581585       15804 2011-12-09 12:31:00
18534    581586       13113 2011-12-09 12:49:00
18535    581587       12680 2011-12-09 12:50:00

In [196]:
invoice_items = df_clean[["InvoiceNo", "StockCode", "Quantity", "UnitPrice", "Revenue"]].copy()
invoice_items = invoice_items.drop_duplicates().reset_index(drop=True)
invoice_items.tail()

       InvoiceNo StockCode  Quantity  UnitPrice  Revenue
392724    581587     22613        12       0.85    10.20
392725    581587     22899         6       2.10    12.60
392726    581587     23254         4       4.15    16.60
392727    581587     23255         4       4.15    16.60
392728    581587     22138         3       4.95    14.85

In [197]:
print("Customers:", len(customers))
print("Products:", len(products))
print("Invoices:", len(invoices))
print("Invoice Items:", len(invoice_items))

print(
    "Exact duplicates:",
    invoice_items.duplicated().sum()
)
print(
    "Invoice + StockCode duplicates:",
    invoice_items.duplicated(
        subset=["InvoiceNo", "StockCode"]
    ).sum()
)

Customers: 4339
Products: 3665
Invoices: 18536
Invoice Items: 392729
Exact duplicates: 0
Invoice + StockCode duplicates: 4854

In [198]:
df_clean.to_csv("G:\ecommerce-sales-prediction\data\processed/online_retail_clean.csv", index=False)
print("File created successfully!")

File created successfully!